# Generated by Django 6.0.3 on 2026-04-06 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.PositiveSmallIntegerField(help_text='Niveau de 0 à 100')),
                ('categorie', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Base de données'), ('other', 'Autre')], default='other', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compétence',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entree', models.CharField(choices=[('formation', 'Formation'), ('experience', 'Expérience')], default='formation', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('etablissement', models.CharField(max_length=300)),
                ('date_debut', models.CharField(max_length=30)),
                ('date_fin', models.CharField(blank=True, default='En cours', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Formation / Expérience',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('pct', models.PositiveSmallIntegerField(default=70, help_text='% pour la barre')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Langue',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
